# Generated by Django 5.1.3 on 2024-11-08 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_testimonial_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='client_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='feedback',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.portfolio'),
        ),
    ]
