# Generated by Django 5.1.3 on 2024-11-08 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_testimonial_client_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='project',
        ),
    ]
